#!/usr/bin/python3

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QTreeView, QTreeWidgetItem, QAction, QFileDialog
from PyQt5.QtGui import QBrush, QColor

from lib.TreeModel import TreeModel
import xml.etree.ElementTree as ET
import sys

class hardware5000(QMainWindow):
    def __init__(self):
        super().__init__()

        self.view = QTreeView(self) 
        self.setCentralWidget(self.view)

        menu = self.menuBar()
        fileMenu = menu.addMenu('&File')
        openButton = QAction("&Open", self)
        openButton.triggered.connect(self.open)
        fileMenu.addAction(openButton)

        if len(sys.argv) == 2:
            self.open(sys.argv[1])

        self.show()

    def open(self, f = None):
        if not f:
            path = QFileDialog.getOpenFileName(self)[0]
        else:
            path = f

        if path:
            self.model = TreeModel(path)
            self.view.setModel(self.model)

app = QApplication(sys.argv)
masterView = hardware5000()
sys.exit(app.exec_())
