#!/usr/bin/python3

from PyQt5.QtWidgets import QApplication, QMainWindow, QTreeView, QHeaderView, QFileDialog
import sys

from lib.TreeModel import TreeModel
from lib.menubar import menubar

class hardware5000(QMainWindow):
    def __init__(self):
        super().__init__()

        self.view = QTreeView(self) 
        self.setCentralWidget(self.view)
        self.view.header().setSectionResizeMode(QHeaderView.ResizeToContents)
        self.model = False

        menubar(self)

        if len(sys.argv) == 2:
            self.open(sys.argv[1])

        self.show()

    def open(self, f = None):
        if not f:
            path = QFileDialog.getOpenFileName(self)[0]
        else:
            path = f

        if path:
            self.model = TreeModel(path)
            self.view.setModel(self.model)

    def save(self):
        if self.model:
            self.model.save()

    def saveAs(self):
        path = QFileDialog.getSaveFileName(self)[0]
        if path != "":
            self.model.save(path)

    def highlight(self):
        if self.model:
            self.model.highlight()

app = QApplication(sys.argv)
masterView = hardware5000()
sys.exit(app.exec_())
